name: Check libstdc++ version

on: [push]

jobs:
  check-libstdc-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Check libstdc++ version
        run: |
            /usr/lib/x86_64-linux-gnu/libstdc++.so.6 --version